# GitHub Actions workflow for automatic deployment to GitHub Pages
name: Deploy to GitHub Pages

# Trigger the workflow on push to main branch
on:
  push:
    branches: [ main ]
  
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and deploy job
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    
    # Configure GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Setup Node.js (if you want to run any build processes)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      # Install dependencies (optional - only if you have build steps)
      - name: Install dependencies
        run: npm ci
      
      # Optional: Run any build commands here if needed
      # - name: Build project
      #   run: npm run build
      
      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # Upload the entire repository as artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository (since it's a static site)
          path: '.'
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4